-- Local seed data intentionally starts empty.
--
-- Suggested local admin bootstrap after creating a user account:
--
-- update public.profiles
-- set role = 'admin'
-- where email = 'admin@example.com';
--
-- update auth.users
-- set raw_app_meta_data = coalesce(raw_app_meta_data, '{}'::jsonb) || '{"role":"admin"}'::jsonb
-- where email = 'admin@example.com';
