import { ArrowRight, PlayCircle, Target, Shield, MousePointer2, Users, Clock, Trophy, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ProgressLink } from "@/components/ui/progress-link";
import { CurrentYear } from "@/components/landing/current-year";
import { hasEnvVars } from "@/lib/supabase/env";

const featureCards = [
  {
    title: "Competition Control Center",
    description: "Centralized dashboard for teachers to manage live heats, time limits, and question banks.",
  },
  {
    title: "Live Leaderboard Engine",
    description: "Instant ranking updates with millisecond precision tracking for high-stakes speed drills.",
  },
  {
    title: "Smart Competition Scheduler",
    description: "Automate seasonal leagues and qualifying rounds with intelligent student-matching logic.",
  },
];

const methodologySteps = [
  {
    phase: "Stage 01",
    title: "Build the Foundation",
    description: "Custom question sets generated by AI to target specific student weaknesses and cognitive gaps.",
    tone: "amber" as const,
  },
  {
    phase: "Stage 02",
    title: "Enter The Arena",
    description: "Students compete in timed environments that simulate high-stakes examinations and speed math bowls.",
    tone: "navy" as const,
  },
  {
    phase: "Stage 03",
    title: "Track Excellence",
    description: "Cross-correlate exam analysis with ELO-style focus metrics, driving real-time grade improvement modeling.",
    tone: "ink" as const,
  },
];

const pricingTiers = [
  {
    name: "Starter",
    price: "$49",
    suffix: "/mo",
    cta: "Select Plan",
    featured: false,
    features: ["Up to 50 students", "10 Competition Tracks", "Basic Leaderboards"],
  },
  {
    name: "Coordinator",
    price: "$149",
    suffix: "/mo",
    cta: "Start Free Trial",
    featured: true,
    features: ["Up to 500 students", "Unlimited Tracks", "Segmented Analytics", "Priority Support"],
  },
  {
    name: "Elite",
    price: "$399",
    suffix: "/mo",
    cta: "Contact Sales",
    featured: false,
    features: ["Unlimited Everything", "Custom Integrations", "Multi-Campus System", "Account Manager"],
  },
];

export function LandingPage() {
  return (
    <div className="min-h-screen bg-[#fafafa] font-sans selection:bg-[#f59700] selection:text-white">
      {/* Spacer for fixed nav */}
      <div className="h-[72px]" />

      {/* Hero Section */}
      <section id="product" className="relative scroll-mt-24 overflow-hidden px-6 py-12 lg:py-20">
        <div className="absolute inset-0 -z-10 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-orange-100/50 via-[#fafafa] to-[#fafafa]" />
        <div className="mx-auto flex max-w-6xl flex-col items-center text-center">
          <div className="mb-8 inline-flex animate-pulse items-center gap-3 rounded-full border border-orange-100 bg-orange-50 px-4 py-2 text-xs font-semibold text-orange-600 shadow-sm">
            <div className="h-1.5 w-1.5 rounded-full bg-[#f59700]" />
            LIVE COMPETITION NOW OPEN
          </div>

          <h1 className="mb-6 max-w-3xl text-4xl font-extrabold leading-[1.1] tracking-tight text-slate-900 md:text-6xl">
            Mathematical excellence,{" "}
            <span className="mt-1 block text-[#f59700]">scaled for schools.</span>
          </h1>

          <p className="mb-10 max-w-2xl text-lg leading-relaxed text-slate-500 md:text-xl">
            The all-in-one platform for modern school administrators to manage competitions, track excellence, and engage students.
          </p>

          <div className="mb-16 flex flex-col items-center gap-4 sm:flex-row">
            <ProgressLink
              href="/auth/sign-up"
              className="flex items-center gap-2 rounded-xl bg-[#f59700] px-6 py-3 text-base font-bold text-white shadow-xl shadow-[#f59700]/30 transition-all hover:scale-105 hover:bg-[#e08900]"
            >
              Start Free Trial <ArrowRight size={18} />
            </ProgressLink>
            <button className="flex items-center gap-2 rounded-xl border-2 border-slate-200 bg-white px-6 py-3 text-base font-bold text-slate-800 shadow-sm transition-all hover:border-slate-300 hover:shadow-md">
              <PlayCircle size={18} className="text-slate-600" /> View Demo
            </button>
          </div>

          <DashboardPreview />
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="scroll-mt-24 bg-slate-100 px-6 py-16">
        <div className="mx-auto max-w-6xl text-center">
          <h2 className="mb-3 text-3xl font-extrabold text-slate-900 md:text-4xl">Every tool your school needs</h2>
          <p className="mx-auto mb-12 max-w-2xl text-lg text-slate-600">Seamlessly integrate competition-grade analytics into your curriculum.</p>
          <div className="grid grid-cols-1 gap-6 text-left md:grid-cols-3">
            {featureCards.map((feature, index) => (
              <article key={feature.title} className="group rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition-shadow hover:shadow-xl">
                <div className="relative mb-6 flex h-40 items-center justify-center overflow-hidden rounded-xl border border-slate-100 bg-slate-50">
                  {index === 0 && <FeatureStackIcon />}
                  {index === 1 && <FeatureLeaderboardIcon />}
                  {index === 2 && <FeatureSchedulerIcon />}
                </div>
                <h3 className="mb-2 text-xl font-bold text-slate-900">{feature.title}</h3>
                <p className="text-sm leading-relaxed text-slate-600">{feature.description}</p>
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* Methodology Section */}
      <section id="methodology" className="scroll-mt-24 overflow-hidden bg-white px-6 py-20">
        <div className="mx-auto mb-12 max-w-6xl text-center">
          <h2 className="mb-3 text-3xl font-extrabold text-slate-900">The Methodology</h2>
          <p className="mx-auto max-w-2xl text-lg text-slate-600">Deep impact in qualitative dimensions.</p>
        </div>
        <div className="mx-auto max-w-4xl space-y-6">
          {methodologySteps.map((step) => (
            <article
              key={step.title}
              className={[
                "group relative flex flex-col items-center justify-between gap-10 overflow-hidden rounded-3xl p-8 md:flex-row md:p-10",
                step.tone === "amber" ? "bg-[#f59700] text-slate-900" : "",
                step.tone === "navy" ? "bg-[#0f172a] text-white" : "",
                step.tone === "ink" ? "bg-[#020617] text-white" : "",
              ].join(" ")}
            >
              <div className="relative z-10 md:w-1/2">
                <div className={`mb-3 text-xs font-bold uppercase tracking-widest ${step.tone === "amber" ? "opacity-80" : "text-[#f59700]"}`}>
                  {step.phase}
                </div>
                <h3 className="mb-4 text-3xl font-extrabold">{step.title}</h3>
                <p className={`text-base font-medium leading-relaxed ${step.tone === "amber" ? "opacity-90" : step.tone === "navy" ? "text-slate-300" : "text-slate-400"}`}>
                  {step.description}
                </p>
              </div>
              <div className="relative z-10 flex justify-end md:w-1/2">
                {step.tone === "amber" && <MethodologyFoundationGraphic />}
                {step.tone === "navy" && <MethodologyArenaGraphic />}
                {step.tone === "ink" && <MethodologyTrackGraphic />}
              </div>
            </article>
          ))}
        </div>
      </section>

      {/* Built for Admin Section */}
      <section className="scroll-mt-24 border-y border-slate-200 bg-slate-50 px-6 py-20">
        <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-12 lg:flex-row">
          <div className="lg:w-1/2">
            <h2 className="mb-5 text-3xl font-extrabold leading-tight text-slate-900 md:text-4xl">
              Built for modern school administrators
            </h2>
            <p className="mb-10 text-lg text-slate-600">
              Stop managing spreadsheets and start managing outcomes. Competition provides the granular data you need to drive whole-school improvement.
            </p>
            <div className="flex gap-6">
              <div className="flex-1 rounded-2xl border border-orange-100 bg-orange-50 p-5">
                <div className="mb-1 text-3xl font-black text-[#f59700]">98%</div>
                <div className="text-xs font-bold uppercase tracking-wide text-slate-700">Engagement Climb</div>
              </div>
              <div className="flex-1 rounded-2xl border border-slate-200 bg-white p-5">
                <div className="mb-1 text-3xl font-black text-slate-900">2.4x</div>
                <div className="text-xs font-bold uppercase tracking-wide text-slate-500">Velocity Increase</div>
              </div>
            </div>
          </div>
          <div className="w-full lg:w-1/2">
            <div className="group relative w-full rounded-2xl border border-slate-100 bg-white p-6 shadow-xl shadow-slate-200">
              <h3 className="mb-6 text-base font-bold text-slate-800">Engagement Metrics</h3>
              <div className="space-y-5">
                <div className="flex items-center gap-4">
                  <Users size={20} className="text-slate-400" />
                  <div className="flex-1 overflow-hidden rounded-full bg-slate-100">
                    <div className="h-3 w-[95%] rounded-full bg-[#f59700]" />
                  </div>
                </div>
                <div className="flex items-center gap-4">
                  <Clock size={20} className="text-slate-400" />
                  <div className="flex-1 overflow-hidden rounded-full bg-slate-100">
                    <div className="h-3 w-[70%] rounded-full bg-slate-800 transition-all duration-1000 group-hover:w-[85%]" />
                  </div>
                </div>
                <div className="flex items-center gap-4">
                  <Trophy size={20} className="text-slate-400" />
                  <div className="flex-1 overflow-hidden rounded-full bg-slate-100">
                    <div className="h-3 w-[88%] rounded-full bg-[#f59700]" />
                  </div>
                </div>
              </div>
              <div className="absolute -inset-0.5 -z-[1] rounded-[24px] bg-gradient-to-r from-[#f59700]/0 via-[#f59700]/20 to-[#f59700]/0 opacity-0 blur transition-opacity duration-1000 group-hover:opacity-100" />
            </div>
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section id="pricing" className="scroll-mt-24 bg-[#0f172a] px-6 py-20 text-white">
        <div className="mx-auto mb-12 max-w-6xl text-center">
          <h2 className="mb-3 text-3xl font-extrabold">Choose Your Track</h2>
          <p className="mx-auto max-w-2xl text-lg text-slate-400">Scale your competition ecosystem at your school&apos;s pace.</p>
        </div>
        <div className="mx-auto grid max-w-5xl grid-cols-1 items-stretch gap-6 md:grid-cols-3">
          {pricingTiers.map((tier) => (
            <article
              key={tier.name}
              className={[
                "relative flex flex-col overflow-hidden rounded-2xl p-6",
                tier.featured
                  ? "border-2 border-orange-400 bg-[#f59700] shadow-2xl shadow-[#f59700]/20 md:-translate-y-3"
                  : "group border border-slate-700 bg-[#1e293b] transition-colors hover:border-slate-500",
              ].join(" ")}
            >
              {tier.featured && (
                <div className="absolute right-0 top-0 rounded-bl-xl rounded-tr-2xl bg-white px-3 py-1 text-[10px] font-black uppercase tracking-wider text-[#f59700]">
                  Most Popular
                </div>
              )}
              <h3 className={`mb-1 text-lg font-bold ${tier.featured ? "text-white/90" : "text-slate-300"}`}>{tier.name}</h3>
              <div className="mb-6 flex items-baseline gap-1">
                <span className={`text-4xl font-black ${tier.featured ? "text-white" : ""}`}>{tier.price}</span>
                <span className={tier.featured ? "text-sm font-medium text-orange-200" : "text-sm font-medium text-slate-400"}>{tier.suffix}</span>
              </div>
              <ul className="mb-10 flex-1 space-y-3">
                {tier.features.map((feature) => (
                  <li key={feature} className={`flex items-center gap-2.5 text-sm ${tier.featured ? "text-white" : "text-slate-300"}`}>
                    <Target size={16} className={tier.featured ? "text-white" : "text-[#f59700]"} />
                    {feature}
                  </li>
                ))}
              </ul>
              <ProgressLink
                href={tier.featured ? "/auth/sign-up" : "/auth/login"}
                className={[
                  "w-full rounded-xl py-3 text-center text-sm font-bold transition-colors",
                  tier.featured
                    ? "bg-white text-[#f59700] shadow-lg hover:bg-orange-50"
                    : "bg-slate-800 text-white hover:bg-slate-700",
                ].join(" ")}
              >
                {tier.cta}
              </ProgressLink>
            </article>
          ))}
        </div>
      </section>

      {/* Footer */}
      <LandingFooter />
    </div>
  );
}

/* ─── Footer ─── */
function LandingFooter() {
  return (
    <footer className="border-t border-slate-800 bg-[#020617] px-6 py-16 text-slate-400 lg:px-12">
      <div className="mx-auto flex max-w-7xl flex-col gap-16">
        <div className="flex flex-col justify-between gap-12 lg:flex-row lg:gap-24">
          <div className="flex max-w-sm flex-col gap-8">
            <ProgressLink href="/" className="flex items-center gap-3">
              <img src="/mathwiz-logo.svg" alt="MathWiz" className="h-10 w-10 object-contain" />
              <span className="text-2xl font-bold tracking-tight text-white">MathWiz</span>
            </ProgressLink>
            <p className="text-base leading-relaxed text-slate-400">
              Empowering educational institutions with the tools for modern excellence management.
            </p>
            <div className="inline-flex w-max items-center gap-2 rounded-full border border-slate-800 bg-[#0f172a] px-4 py-2 shadow-sm">
              <div className="h-2 w-2 animate-pulse rounded-full bg-green-500" />
              <span className="text-xs font-bold tracking-wider text-slate-300">SYSTEMS OPERATIONAL</span>
            </div>
          </div>
          <div className="flex flex-wrap gap-16 lg:flex-nowrap lg:gap-24">
            <div className="flex flex-col gap-6">
              <h4 className="text-lg font-bold text-white">Product</h4>
              <nav className="flex flex-col gap-4 text-base text-slate-400">
                <a href="#features" className="transition-colors hover:text-white">Features</a>
                <a href="#" className="transition-colors hover:text-white">API</a>
                <a href="#" className="transition-colors hover:text-white">Security</a>
              </nav>
            </div>
            <div className="flex flex-col gap-6">
              <h4 className="text-lg font-bold text-white">Company</h4>
              <nav className="flex flex-col gap-4 text-base text-slate-400">
                <a href="#" className="transition-colors hover:text-white">About</a>
                <a href="#" className="transition-colors hover:text-white">Blog</a>
                <a href="#" className="transition-colors hover:text-white">Careers</a>
              </nav>
            </div>
            <div className="flex flex-col gap-6">
              <h4 className="text-lg font-bold text-white">Support</h4>
              <nav className="flex flex-col gap-4 text-base text-slate-400">
                <a href="#" className="transition-colors hover:text-white">Help Center</a>
                <a href="#" className="transition-colors hover:text-white">Guides</a>
                <a href="#" className="transition-colors hover:text-white">Contact</a>
              </nav>
            </div>
          </div>
        </div>
        <div className="flex flex-col items-center justify-between gap-6 border-t border-[#0f172a] pt-8 md:flex-row">
          <p className="text-sm font-medium text-slate-500">© <CurrentYear /> MathWiz Arena. All rights reserved.</p>
          <div className="flex flex-wrap items-center justify-center gap-6 text-sm font-medium text-slate-500">
            <ProgressLink href="/privacy" className="transition-colors hover:text-white">Privacy Policy</ProgressLink>
            <ProgressLink href="/terms" className="transition-colors hover:text-white">Terms of Service</ProgressLink>
          </div>
        </div>
      </div>
    </footer>
  );
}

/* ─── Dashboard Preview ─── */
function DashboardPreview() {
  return (
    <div className="w-full max-w-4xl overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-2xl shadow-slate-200/50">
      <div className="flex items-center justify-between border-b border-slate-100 bg-slate-50/50 px-5 py-3">
        <div className="flex items-center gap-2">
          <div className="h-2.5 w-2.5 rounded-full bg-red-400" />
          <div className="h-2.5 w-2.5 rounded-full bg-amber-400" />
          <div className="h-2.5 w-2.5 rounded-full bg-emerald-400" />
        </div>
        <div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-wider text-slate-400">
          <Target size={12} /> Live Admin Dashboard
        </div>
        <div className="flex items-center gap-4">
          <div className="rounded-full bg-emerald-100 px-2.5 py-0.5 text-[10px] font-bold text-emerald-700">Active: 1,240 students</div>
          <div className="font-mono text-[10px] text-slate-400">{hasEnvVars ? "v2.4.0" : "Setup pending"}</div>
        </div>
      </div>
      <div className="grid grid-cols-1 gap-6 bg-white p-6 lg:grid-cols-3">
        <div className="space-y-6 lg:col-span-2">
          <div className="mb-4 flex items-end justify-between">
            <div className="space-y-1"><div className="text-xs font-medium uppercase tracking-wider text-slate-400">Completion</div><div className="text-2xl font-bold text-slate-800">84.2%</div></div>
            <div className="space-y-1 text-center"><div className="text-xs font-medium uppercase tracking-wider text-slate-400">Accuracy</div><div className="text-2xl font-bold text-slate-800">92%</div></div>
            <div className="space-y-1 text-right"><div className="text-xs font-medium uppercase tracking-wider text-slate-400">Avg Time</div><div className="text-2xl font-bold text-[#f59700]">14:22</div></div>
          </div>
          <div className="flex h-40 items-end justify-between gap-2 border-b-2 border-slate-100 pb-2">
            {[40, 65, 45, 80, 95, 60, 85, 45, 75, 50].map((h, i) => (
              <div key={i} className="group relative w-full cursor-pointer rounded-t-sm bg-[#f59700]/20 transition-colors hover:bg-[#f59700]" style={{ height: `${h}%` }}>
                <div className="absolute -top-8 left-1/2 -translate-x-1/2 whitespace-nowrap rounded bg-slate-800 px-1.5 py-0.5 text-[10px] font-bold text-white opacity-0 transition-opacity group-hover:opacity-100">Day {i + 1}</div>
              </div>
            ))}
          </div>
        </div>
        <div className="space-y-5">
          <h3 className="border-b border-slate-100 pb-2 text-xs font-bold uppercase tracking-wide text-slate-800">Live Leaderboard</h3>
          {[
            { name: "Euler High", score: "9,420", pos: 1 },
            { name: "Fermat Prep", score: "8,915", pos: 2 },
            { name: "Gauss Academy", score: "8,704", pos: 3 },
          ].map((item, i) => (
            <div key={i} className="flex items-center gap-3">
              <div className={`flex h-7 w-7 items-center justify-center rounded-full text-xs font-bold ${i === 0 ? "bg-amber-100 text-amber-600" : i === 1 ? "bg-slate-200 text-slate-600" : "bg-orange-100 text-orange-600"}`}>{item.pos}</div>
              <div className="flex-1">
                <div className="text-sm font-bold text-slate-800">{item.name}</div>
                <div className="mt-1.5 h-1.5 w-full rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#f59700]" style={{ width: `${100 - i * 15}%` }} /></div>
              </div>
              <div className="font-mono text-xs font-semibold text-slate-500">{item.score}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

/* ─── Feature Icons ─── */
function FeatureStackIcon() {
  return (
    <>
      <div className="absolute h-28 w-20 -rotate-6 rounded-lg bg-[#f59700]/40 shadow-lg transition-transform duration-500 group-hover:scale-110" />
      <div className="absolute h-28 w-20 rotate-3 rounded-lg bg-[#f59700]/70 shadow-lg transition-transform delay-75 duration-500 group-hover:scale-105" />
      <div className="relative flex h-28 w-20 items-center justify-center rounded-lg bg-[#f59700] shadow-xl transition-transform delay-150 duration-500 group-hover:-translate-y-2">
        <Shield size={28} className="text-white" />
      </div>
    </>
  );
}

function FeatureLeaderboardIcon() {
  return (
    <div className="flex w-full flex-col justify-center gap-2.5 p-5">
      <div className="flex h-6 w-full items-center rounded bg-slate-800 px-3 transition-transform duration-500 group-hover:translate-x-2">
        <div className="h-1.5 w-20 rounded-full bg-[#f59700]" />
      </div>
      <div className="flex h-6 w-[85%] items-center rounded bg-slate-800 px-3 transition-transform delay-75 duration-500 group-hover:translate-x-4">
        <div className="h-1.5 w-14 rounded-full bg-[#f59700]" />
      </div>
      <div className="flex h-6 w-[90%] items-center rounded bg-slate-800 px-3 transition-transform delay-150 duration-500 group-hover:translate-x-1">
        <div className="h-1.5 w-16 rounded-full bg-[#f59700]" />
      </div>
    </div>
  );
}

function FeatureSchedulerIcon() {
  return (
    <>
      <div className="grid h-full w-full grid-cols-3 gap-1.5 opacity-20">
        <div className="rounded bg-slate-800" />
        <div className="rounded bg-[#f59700]" />
        <div className="rounded bg-slate-800" />
        <div className="rounded bg-slate-800" />
        <div className="rounded bg-[#f59700]" />
        <div className="rounded bg-slate-800" />
      </div>
      <MousePointer2
        size={28}
        className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 fill-[#f59700] text-[#f59700] drop-shadow-md transition-transform duration-700 ease-out group-hover:translate-x-3 group-hover:translate-y-3"
      />
    </>
  );
}

/* ─── Methodology Graphics ─── */
function MethodologyFoundationGraphic() {
  return (
    <div className="relative flex h-48 w-48 items-center justify-center rounded-full border-2 border-slate-900 transition-transform duration-700 group-hover:scale-105">
      <div className="absolute h-0.5 w-full bg-slate-900" />
      <div className="absolute h-full w-0.5 bg-slate-900" />
      <div className="absolute h-0.5 w-[141%] -rotate-45 bg-slate-900" />
      <div className="absolute right-[14%] top-[14%] h-3 w-3 rounded-full bg-slate-900" />
      <div className="absolute right-[-5%] top-[5%] text-lg font-bold italic font-serif">cos θ, sin θ</div>
    </div>
  );
}

function MethodologyArenaGraphic() {
  return (
    <div className="flex gap-2 rounded-lg border border-slate-700 bg-slate-800/50 p-3 backdrop-blur transition-transform duration-500 group-hover:translate-x-2">
      {[1, 2, 3, 4, 5].map((i) => (
        <div key={i} className={`h-16 w-10 rounded ${i === 5 ? "bg-[#f59700]/80" : "bg-slate-700"}`} />
      ))}
    </div>
  );
}

function MethodologyTrackGraphic() {
  return (
    <div className="relative flex h-36 w-48 items-center justify-center border-b-2 border-l-2 border-slate-700">
      <svg viewBox="0 0 100 100" className="absolute inset-0 h-full w-full origin-bottom overflow-visible fill-none stroke-[#f59700] stroke-2 stroke-linecap-round stroke-linejoin-round transition-transform duration-700 group-hover:scale-y-110">
        <path d="M 10 80 Q 30 20 50 50 T 90 20" />
        <path d="M 10 90 Q 40 80 60 40 T 90 40" className="stroke-slate-500 opacity-50" />
      </svg>
    </div>
  );
}
